# Generated by Django 4.1 on 2022-09-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
            ],
        ),
    ]
